<a href="https://colab.research.google.com/github/tkowal0007/machine-learning-bootcamp/blob/main/02algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1)

4.123105625617661

In [7]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [9]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

In [11]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [14]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])

print(X, '/n')
print(Y)

[[5 3]
 [3 9]] /n
[[ 1]
 [-1]]


In [17]:
Z = np.dot(X,Y)

In [18]:
print(Z)

[[ 2]
 [-6]]


In [19]:
Z.shape

(2, 1)

In [23]:
X = np.array([[2,-1,3],
              [3,1,0]])
Y = np.array([[2,1,-1],
              [0,1,1],
              [3,2,0]])


print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0  1  1]
 [ 3  2  0]]


In [24]:
Z = np.dot(X,Y)
print(Z)

[[13  7 -3]
 [ 6  4 -2]]


In [26]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [27]:
np.trace(A)

5

In [29]:
np.eye(5,dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
A

array([[ 2,  4],
       [-1,  3]])

In [31]:
B = np.linalg.inv(A)

In [33]:
np.set_printoptions(precision=4, suppress = True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [35]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [36]:
A = np.array([[2,4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [38]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [39]:
A_inv = np.linalg.inv(A)

In [40]:
X = np.dot(A_inv,B)

In [41]:
X

array([[1.],
       [2.]])