<a href="https://colab.research.google.com/github/tkowal0007/machine-learning-bootcamp/blob/main/wprowadzenie/01npintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello")

hello


In [3]:
import numpy as np
np.__version__

'1.26.4'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x= np.array([1.1, 1.3, 3.4])
print(x)

[1.1 1.3 3.4]


In [14]:
x.shape

(3,)

In [15]:
x.dtype

dtype('float64')

In [16]:
x = np.array([[1,2], [-3,1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x.dtype

dtype('int64')

In [20]:
x = np.array([[1,2,3], [4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [21]:
x.shape

(2, 3)

In [22]:
x.ndim

2

In [23]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

     [[4,1,3],
      [4,2,1]],


     [[4,1,3],
      [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [24]:
x.ndim

3

In [25]:
x.shape

(3, 2, 3)

In [26]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [27]:
A = np.array([1.2,2.3,3.4])
A.dtype

dtype('float64')

In [28]:
A = np.array([1.0,2.0,3.0], dtype = 'float')
A.dtype

dtype('float64')

In [29]:
A = np.array([1,2,3], dtype = 'float')
A.dtype

dtype('float64')

In [30]:
A = np.array([1,2,3], dtype = 'complex')
A.dtype
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [31]:
A = np.array([1.2,2.3,3.4], dtype='int')
A.dtype
A

array([1, 2, 3])

In [32]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [33]:
A = np.array([24,120,230], dtype = np.int8)
A.dtype

<ipython-input-33-8c65c080e3f0>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24,120,230], dtype = np.int8)


dtype('int8')

In [34]:
A = np.array([24,120,230], dtype = np.uint8)
A.dtype

dtype('uint8')

In [35]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.zeros(shape=(4,10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.ones(shape=(5,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.full(shape = (3,3), fill_value= 4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [42]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [44]:
np.arange(start=0, stop = 1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [45]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
A = np.arange(15)

In [47]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
A.reshape((3,5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
A = np.array([1,2,3,4])
B = np.array([3,-1,3,2])

In [52]:
print(A)
print(B)

[1 2 3 4]
[ 3 -1  3  2]


In [53]:
A + B

array([4, 1, 6, 6])

In [54]:
A - B

array([-2,  3,  0,  2])

In [55]:
A * B

array([ 3, -2,  9,  8])

In [56]:
A / B

array([ 0.33333333, -2.        ,  1.        ,  2.        ])

In [57]:
A + 3

array([4, 5, 6, 7])

In [58]:
A - 4

array([-3, -2, -1,  0])

In [59]:
2 * A

array([2, 4, 6, 8])

In [60]:
A + 3 * B

array([10, -1, 12, 10])

In [61]:
np.add(A,B)

array([4, 1, 6, 6])

In [62]:
np.subtract(A,B)

array([-2,  3,  0,  2])

In [63]:
np.multiply(A,B)

array([ 3, -2,  9,  8])

In [64]:
np.divide(A,B)

array([ 0.33333333, -2.        ,  1.        ,  2.        ])

In [65]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [66]:
X * Y

array([[6, 0],
       [2, 0]])

In [67]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [68]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [69]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [70]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [71]:
np.random.seed(0)

In [72]:
np.random.randn()

1.764052345967664

In [73]:
np.random.rand(10)

array([0.60276338, 0.54488318, 0.4236548 , 0.64589411, 0.43758721,
       0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492])

In [74]:
np.random.rand(10,4)

array([[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677, 0.43860151]])

In [76]:
np.random.rand()

0.10204481074802807

In [77]:
np.random.rand(10)

array([0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077,
       0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295])

In [78]:
np.random.rand(10,2)

array([[0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212]])

In [80]:
np.random.randint(10)

4

In [81]:
np.random.randint(low=10, high = 101)

91

In [82]:
np.random.randint(low=10, high = 101, size = 10)

array([60, 37, 24, 51, 68, 75, 46, 20, 96, 53])

In [85]:
np.random.choice([4,2,3,5,6])

3

In [88]:
np.random.choice(['python', 'sql', 's'])

's'

In [89]:
data = np.arange(10)

In [90]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.random.shuffle(data)

In [92]:
data

array([1, 5, 4, 9, 7, 2, 8, 3, 6, 0])

In [93]:
np.exp(1)

2.718281828459045

In [94]:
np.exp(1)

2.718281828459045

In [95]:
np.sqrt(25)

5.0

In [96]:
np.all([2,3,1])

True

In [98]:
np.any([0,0,0,0,0])

False

In [99]:
bool(0)

False

In [100]:
bool(1)

True

In [102]:
A = np.random.rand(5)
A

array([0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [103]:
np.argmax(A)

4

In [104]:
A[np.argmax(A)]

0.896038387509077

In [105]:
np.argmin(A)

0

In [106]:
np.argsort(A)

array([0, 3, 1, 2, 4])

In [107]:
np.max(A)

0.896038387509077

In [108]:
np.min(A)

0.28847643704852866

In [109]:
np.mean(A)

0.5540015711656106

In [110]:
np.median(A)

0.43328806198204406

In [111]:
np.std(A)

0.23144954668752118

In [112]:
A = np.arange(20)

In [113]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [114]:
A[2]

2

In [115]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [116]:
A[:2]

array([0, 1])

In [117]:
A[[0,2]]

array([0, 2])

In [118]:
A[-1]

19

In [120]:
A[10:15]

array([10, 11, 12, 13, 14])

In [124]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
A[0]

array([0, 1, 2, 3, 4])

In [125]:
A[1]

array([5, 6, 7, 8, 9])

In [126]:
A[:,-1]

array([ 4,  9, 14, 19])

In [127]:
A[1,1]

6

In [131]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [133]:
A[1,2] = 14

In [134]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [135]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
for i in A:
  print(i)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [138]:
for i in A:
  print(i[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [139]:
for row in A.flat:
  print(row)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [140]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [142]:
np.shape(A)

(4, 5)

In [143]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [144]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [145]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [146]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [147]:
A = np.arange(start= - 10, stop = 10, step = 0.5)

In [148]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [151]:
A = A.reshape(10,-1)

In [152]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [155]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [156]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [157]:
np.bitwise_or(A < -6, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [158]:
A[np.bitwise_or(A < -6, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,   5.5,
         6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5])